---
title: "NewtonRAphson"
author: |submitted to: "msm"
date: "1/4/2022"
output:
   pdf_document:
     toc: true
     toc_depth: 2
     number_sections: true
    
---

1.Newton rafson method Rpubs

2.Newton raphson method using for loop mine

3.Newtoon raphson using while loop
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = F,comment = NA,message = F)
```
1.Newton rafson method Rpubs

```{r comment=NA}
newton.raphson <- function(f, a, b, tol, n) {
  require(numDeriv) # Package for computing f'(x)
  x0 <- a # Set start value to supplied lower bound
  k <- n # Initialize for iteration results
  for (i in 1:n) {
    dx <- genD(func = f, x = x0)$D[1] # First-order derivative f'(x0)
    x1 <- x0 - (f(x0) / dx) # Calculate next value x1
    k[i] <- x1 # Store x1
    # Once the difference between x0 and x1 becomes sufficiently small, output the results.
    if (abs(x1 - x0) < tol) {
      root.approx <- tail(k, n=1)
      res <- list('root approximation' = root.approx, 'iterations' = k)
      return(res)
    }
    x0 <- x1
  }
}
func2=function(x) x^4+3*x+log(x)
newton.raphson(func2, 2, 3,tol = .001,n=20)
```
2.Newton raphson method using for loop mine
```{r comment=NA}
newton=function(f,a,b,n){
  require(Deriv)
  k=n
  fp=Deriv(f)
  x0=a
  for(i in 1:n){
    div=f(x0)/fp(x0)
    x1=x0-div
    k[i]=x1
    if(abs(x0-x1)<b){
      m=tail(k,n=1)
      res=list(iter=k,root=x1)
      return(res)
    }
    x0=x1
  }
  
}
f=function(x)  x^2
newton(f,.5,.001,200)
```
3.Newtoon raphson using while loop
```{r comment=NA}

NWton=function(f,initialvalue,tolertance,iteration){
  require(Deriv)
  fpi=Deriv(f)
  x0=initialvalue
  s=iteration
  i=0
  while(i<iteration){
    xn=x0-f(x0)/fpi(x0)
    s[i]=xn
    i=i+1
    if(abs(xn-x0)<tolertance) break
    x0=xn
  }
  
  return(list(root=xn,S=na.omit(s)))
}
f=function(x) x^4+3*x+log(x)
NWton(f,2,.001,20)
```

```{r error=TRUE}

######################
## Maximum likelihood estimate using optim function :

set.seed(18)
dat <- rexp(100, rate = 5)
datn <- rnorm(100, mean = 10, sd = 5)
#mean(dat)

ll_norm <- function(par, y) {
  sd1 <- sum(y - par)^2/(length(y) - 1)
  -sum(dnorm(x = y, mean = par, sd = sd1, log = T))
}


ll <- function(par, y){
  #n <- length(y)
  -sum(dexp(x = y, rate = 1/par, log = T))
  #return((n*log(par)) + (sum(y)/par))
}
##
optim(par = 0.1, fn = ll, y = dat, method = "BFGS")
optim(par = 1, fn = ll_norm, y = datn, method = "BFGS")

#############################################################
##  Maximum likelihood estimate using score and hessian :

score <- function(theta, dat){
  u <- -(100/theta) + (sum(dat)/(theta^2))
  return(u)
}

hess <- function(theta, dat){
  h <- (100/(theta^2)) - ((2*sum(dat)) / (theta^3))
  return(h)
}

#theta0=as.double(readline(prompt = "Enter a point on function:"))

my_optim <- function(theta0, dat){
n=1
while(n<1000){
  n=n+1
  uth=score(theta0, dat)
  hes=hess(theta0, dat)
  if(uth<0.00001){
    break(0)
  }
  theta1=theta0-(uth/hes)
  if(abs((theta1-theta0))<0.00001){
    print("Convergent")
    
    break(0)
  }
  
  theta0=theta1
  print(paste("Iteration number:",n,"Solve",theta0))
}
return(theta0)
}



#####
data=rpois(3,.2)

score_f <- function(theta, dat){
  n <- length(dat)
  u <- -(n/theta) + (sum(dat)/(theta^2))
  return(u)
}
score_f(.01,data)

hess_f <- function(theta, dat){
  n <- length(dat)
  h <- (n/(theta^2)) - ((2*sum(dat))/(theta^3))
  return(h)
}

my_optim <- function(par, dat) {
  ###
  for(r in 1:100) {
    U <- score_f(par, dat)
    H <- hess_f(par, dat)
    par1 <- par - U/H 
    change <- abs(par - par1)
    cat("r=", r, "par=", par1, "change=", change, "\n")
    if (change < .000001) return(par)
    else par <- par1
  }
  cat("program did not converge!")
}

my_optim(.01, data)
data




#######################################

newton_r<- function(par, dat,tol) {
  r=0
  repeat{
    U <- score_f(par, dat)
    H <- hess_f(par, dat)
    par1 <- par - U/H 
    change <- abs(par - par1)
    cat("r=", r, "par=", par1, "change=", change, "\n")
    if (change < tol) return(par)
    else par <- par1
    r=r+1
  }
  cat("program did not converge!")
}

newton_r(.01, dat=rpois(1000,3),.000000006)
```


